### ISSUE TITLE
关于libio里面的多进程模型

### ISSUE THREAD

**Issue by CS-Jackson** [wxggg/libio#1]
请问你是否有测试过多进程模型下和Nignx的差距？我之前写过多线程的简单模型，现在想多了解一下多进程和多线程模式的区别。

**Comment by wxggg** [comment]
你好，就httpserver而言，我这里只实现了多线程的结构，多进程httpserver的话，结构应该会比多线程要简单，与客户端建立连接之后可以直接进行io了，不用像多线程一样进行连接的分发。但是多进程会出现惊群的问题，还需要做负载均衡，可以仿照nginx解决
